baseURL = "http://aftoncoombs.com/"
languageCode = "en-us"
title = "Afton Coombs"
theme = 'gruvhugo'

[params.main]
  enabled = true
  enableKatex = true
  metaKeywords = "fast, hugo, theme, minimal, gruvbox"
  headerTitle = "Afton Coombs"
  name = "afton_coombs"
  img = "img/glasses.jpg"
  img_title = ""
  icon = "img/logo.png"
  quote = "Georgia Tech | Formerly Spotify, Hulu"
  description= "Hi there! My name is Afton and I'm a data scientist, developer, artist, and educational researcher with eight years of experience in the field. I am currently enrolled as a master's student in computer science at the Georgia Institute of Technology while continuing to work part-time as a developer and data science consultant. My interests include machine learning, experimentation, data/analytics engineering, tooling development for data science, data visualization, and interactive design. While at GT, I am specializing in interactive intelligence and carrying out research concerned with student opportunities and outcomes in the field of computer science. When I’m not working on software or data, you can often find me practicing my other love (👞👞🎵) on the dance floor or in the studio."
  licenseUrl = ""
  
# Social icons
    
  [[params.social]]
    name = "github"
    url  = "https://github.com/aftonsteps"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/aftoncoombs"

  [[params.social]]
    name = "email"
    url  = "mailto:aftoncoombs@gmail.com"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/aftonsteps"
    
    [[params.social]]
    name = "mastodon"
    url  = "https://mastodon.social/@aftonsteps"

    [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/afton.steps/"
 
    [[params.social]]
    name = "twitch"
    url  = "https://www.twitch.tv/aftonsteps"
    
   #[[params.social]]
   #name = "stackoverflow"
   #url = "https://stackoverflow.com/users/8916690/aftonsteps"

[menu]
  [[menu.main]]
    identifier = "experience"
    name       = "Experience"
    url        = "uploads/Afton Coombs Resume for Web.pdf"
    weight = 10

  [[menu.main]]
    identifier = "portfolio"
    name       = "Portfolio"
    url        = "uploads/portfolio.html"
    weight = 20

  [[menu.main]]
    identifier = "github"
    name       = "Github"
    url        = "https://www.github.com/aftonsteps"


